MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "HRNET-W18"
  FCOS:
    NUM_CLASSES: 2
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  WEIGHT: "pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
DATASETS:
  TRAIN: ("kpt_coco_2017_train",)
  TEST: ("kpt_coco_2017_val",)
  # ROOT: '/depudata1/coco'
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
OUTPUT_DIR: "/mnt/depuazure/fcos_hrnet_w18_5l_2x_person_det1"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 16
  WARMUP_METHOD: "linear"
  WARMUP_FACTOR: 0.0002
  WARMUP_ITERS: 5000